# Generated by Django 5.0.1 on 2024-09-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe_info',
            name='No_of_Tables',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Vibe_Check_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_vector', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.IntegerField(default=-1)),
                ('song_name', models.CharField(max_length=255)),
                ('song_Id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vibe_check_parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vibe_check_parameters')),
            ],
        ),
        migrations.DeleteModel(
            name='Spotify_Cred',
        ),
    ]
