# Generated by Django 5.0.6 on 2024-09-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cafe_info_no_of_tables_vibe_check_parameters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibe_check_parameters',
            old_name='playlist_vector',
            new_name='Playlist_Vector',
        ),
        migrations.CreateModel(
            name='Tables_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.IntegerField()),
                ('Table_Status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.IntegerField(default=-1)),
                ('Track_Name', models.CharField(max_length=255)),
                ('Track_Id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Song_Queue',
        ),
    ]
