# Generated by Django 5.0.6 on 2024-09-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_playlist_vector_vibe_check_parameters_playlist_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_api_parameters',
            name='expires_at',
            field=models.CharField(),
        ),
    ]
