# Generated by Django 5.0.6 on 2024-10-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_spotify_api_parameters_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_api_parameters',
            name='expires_at',
            field=models.CharField(max_length=500),
        ),
    ]
