# Generated by Django 5.0.6 on 2024-10-21 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_vibe_check_parameters_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe_Check_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_Vector', models.BinaryField(default=b'\x80\x04\x95:\x00\x00\x00\x00\x00\x00\x00\x8c\x15managequeue.CafeQueue\x94\x8c\tCafeQueue\x94\x93\x94)R\x94}\x94\x8c\x07myQueue\x94}\x94sb.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
