# Generated by Django 5.0.6 on 2024-10-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vibe_check_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibe_check_parameters',
            old_name='Playlist_Vector',
            new_name='playlist_vector',
        ),
    ]
