# Generated by Django 5.0.6 on 2024-11-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_table_status_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_queue',
            name='current_track',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='table_status_data',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
