# Generated by Django 5.0.6 on 2024-11-18 22:36

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_track_queue_current_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_queue',
            name='current_track',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
